coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto
        branches:
          - main
        if_ci_failed: error
        informational: true
        only_pulls: false
    patch: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - "main"

parsers:
  solidity:
    enable_partials: yes

ignore:
  - "test/**/*"

flags:
  foundry:
    paths:
      - "src/"
    carryforward: true

fixes:

github_checks:
  annotations: true